name: Metrics

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '30 19 * * *'

jobs:
  github-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN  }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          plugin_reactions: yes
          plugin_reactions_limit: 200       
          plugin_reactions_days: 14     
          plugin_reactions_details: count, percentage 
          plugin_reactions_ignored: bot 
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes  
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0  
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}   
          plugin_wakatime_days: 7                                
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_limit: 4                                
          plugin_wakatime_url: https://wakatime.com       
          plugin_wakatime_user: tubone          
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered 
          plugin_topics_limit: 0
          plugin_skyline: yes
          plugin_skyline_year: 0            # Set to 0 to display current year
          plugin_skyline_frames: 60         # Use 60 frames (half-loop)
          plugin_skyline_quality: 0.5       # Set image quality
          plugin_skyline_compatibility: yes # Support additional browsers (⚠️ increases file size and reduce optimization)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_followup: yes
          plugin_followup_sections: repositories, user #
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Asia/Tokyo # Set timezone
          plugin_notable: yes
          plugin_notable_repositories: yes     # Display repositories name instead of only organization name
